### ISSUE TITLE
How to create apiId/apiKey

### ISSUE THREAD

**Issue by sivkov-aspose** [opensearch-project/security-dashboards-plugin#192]
Hello
I'm not sure if this is right place to ask questions, but is it possible to configure apiId/apiKey pair to allow applications to access Elasticsearch indexes as stated in [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html)

If I try to add apiKey in opendistro I get following error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "Unexpected exception indices:data/write/index"
      }
    ],
    "type" : "security_exception",
    "reason" : "Unexpected exception indices:data/write/index"
  },
  "status" : 500
}
```
and in console:
```
odfe-node1    | [2020-05-09T15:29:13,585][ERROR][c.a.o.s.f.OpenDistroSecurityFilter] [odfe-node1] Unexpected exception [_security] InvalidIndexNameException[Invalid index name [_security], must not start with '_'.]
odfe-node1    | org.elasticsearch.indices.InvalidIndexNameException: Invalid index name [_security], must not start with '_'.
odfe-node1    |         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.validateAliasOrIndex(IndexNameExpressionResolver.java:768) ~[elasticsearch-7.6.1.jar:7.6.1]
odfe-node1    |         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:708) ~[elasticsearch-7.6.1.jar:7.6.1]
odfe-node1    |         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:687) ~[elasticsearch-7.6.1.jar:7.6.1]
odfe-node1    |         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:163) ~[elasticsearch-7.6.1.jar:7.6.1]
odfe-node1    |         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:142) ~[elasticsearch-7.6.1.jar:7.6.1]
odfe-node1    |         at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:102) ~[elasticsearch-7.6.1.jar:7.6.1]
odfe-node1    |         at com.amazon.opendistroforelasticsearch.security.resolver.IndexResolverReplacer.resolveIndexPatterns(IndexResolverReplacer.java:253) ~[opendistro_security-1.6.0.0.jar:1.6.0.0]
odfe-node1    |         at com.amazon.opendistroforelasticsearch.security.resolver.IndexResolverReplacer.access$300(IndexResolverReplacer.java:110) ~[opendistro_security-1.6.0.0.jar:1.6.0.0]
odfe-node1    |         at com.amazon.opendistroforelasticsearch.security.resolver.IndexResolverReplacer$2.provide(IndexResolverReplacer.java:331) ~[opendistro_security-1.6.0.0.jar:1.6.0.0]
odfe-node1    |         at com.amazon.opendistroforelasticsearch.security.resolver.IndexResolverReplacer.getOrReplaceAllIndices(IndexResolverReplacer.java:775) ~[opendistro_security-1.6.0.0.jar:1.6.0.0]
odfe-node1    |         at com.amazon.opendistroforelasticsearch.security.resolver.IndexResolverReplacer.resolveRequest(IndexResolverReplacer.java:326) ~[opendistro_security-1.6.0.0.jar:1.6.0.0]
odfe-node1    |         at com.amazon.opendistroforelasticsearch.security.privileges.PrivilegesEvaluator.evaluate(PrivilegesEvaluator.java:186) ~[opendistro_security-1.6.0.0.jar:1.6.0.0]
odfe-node1    |         at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:252) [opendistro_security-1.6.0.0.jar:1.6.0.0]
odfe-node1    |         at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:119) [opendistro_security-1.6.0.0.jar:1.6.0.0]
odfe-node1    |         at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:151) [elasticsearch-7.6.1.jar:7.6.1]
```

**Comment by lorenzo95** [comment]
Same here. Any updates on this? Still not working for me on 1.9.0
Thank you

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
