### ISSUE TITLE
Getting Cannot read property 'init' of undefined for Kibana Login

### ISSUE THREAD

**Issue by firoshaq** [opensearch-project/security-dashboards-plugin#663]
I have an open distro enabled elk stack and I get the below error while logging in.

```
Cannot read property 'init' of undefined
Version: 7.2.0
Build: 24337
TypeError: Cannot read property 'init' of undefined
    at Plugin.start (https://logging.example.com/bundles/kibana.bundle.js:3:2075012)
    at Object.__kbnBundles__.kibana (https://logging.example.com/bundles/kibana.bundle.js:3:2073125)
    at __webpack_require__ (https://logging.example.com/bundles/kibana.bundle.js:3:10344)
    at Object.__kbnBundles__.kibana (https://logging.example.com/bundles/kibana.bundle.js:3:632775)
    at __webpack_require__ (https://logging.example.com/bundles/kibana.bundle.js:3:10344)
    at Object.__kbnBundles__.kibana (https://logging.example.com/bundles/kibana.bundle.js:3:543659)
    at __webpack_require__ (https://logging.example.com/bundles/kibana.bundle.js:3:10344)
    at Object.requireLegacyFiles (https://logging.example.com/bundles/kibana.bundle.js:3:543010)
    at LegacyPlatformService.setup (https://logging.example.com/bundles/commons.bundle.js:27:1756782)
    at CoreSystem._callee$ (https://logging.example.com/bundles/commons.bundle.js:27:1750302)

```
Have tried from multiple machines and experiencing the same issue. Also attaching the screenshot below for this issue.

Any help would be highly appreciated.

**Comment by zengyan-amazon** [comment]
@firoshaq can you provide the Kibana version as well as security Kibana plugin version?

**Comment by firoshaq** [comment]
Hi @zengyan-amazon 

Sure, the elastic version is `7.2.0` and the opendistro plugin version is `1.2.0`.

**Comment by firoshaq** [comment]
Hi @zengyan-amazon 

Could you please let me know if there is an update to this issue?

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
