### ISSUE TITLE
Unknown kid when kid contains / 

### ISSUE THREAD

**Issue by yurippe** [opensearch-project/security-dashboards-plugin#809]
When using OpenID Connect I get this error if the kid contains a `/`
```
com.amazon.dlic.auth.http.jwt.keybyoidc.BadCredentialsException: Unknown kid J4j+I06r0I0vpYnBNucugV8xAPV5\/Xv4uYrrpwwSNK0=
	at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet.getKeyWithKeyId(SelfRefreshingKeySet.java:118) ~[opendistro_security_advanced_modules-0.7.0.0.jar:0.7.0.0]
	at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet.getKey(SelfRefreshingKeySet.java:58) ~[opendistro_security_advanced_modules-0.7.0.0.jar:0.7.0.0]
	at com.amazon.dlic.auth.http.jwt.keybyoidc.JwtVerifier.getVerifiedJwtToken(JwtVerifier.java:41) ~[opendistro_security_advanced_modules-0.7.0.0.jar:0.7.0.0]
	at com.amazon.dlic.auth.http.jwt.AbstractHTTPJwtAuthenticator.extractCredentials0(AbstractHTTPJwtAuthenticator.java:103) 
```
It seems that the forward-slash in the kid is escaped wrong. The real kid should not have `\/` but rather just the `/`

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)).

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
