### ISSUE TITLE
[PR Check] PRs are blocked on ESLint failures

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security-dashboards-plugin#904]
This seems to have started happening to all PRs in that past several days.

<details><summary>ERROR: Configuration for rule "@osd/eslint/require-license-header" is invalid:
	Value ... should NOT have additional properties.</summary>

See failed run at  https://github.com/opensearch-project/security-dashboards-plugin/runs/5196386891?check_suite_focus=true
```
yarn run v1.22.17
$ yarn run lint:es && yarn run lint:sass
$ node ../../scripts/eslint
Error: .eslintrc.js#overrides[0]:
	Configuration for rule "@osd/eslint/require-license-header" is invalid:
	Value {"license":"\n/*\n *   Copyright OpenSearch Contributors\n *\n *   Licensed under the Apache License, Version 2.0 (the \"License\").\n *   You may not use this file except in compliance with the License.\n *   A copy of the License is located at\n *\n *       http://www.apache.org/licenses/LICENSE-2.0\n *\n *   or in the \"license\" file accompanying this file. This file is distributed\n *   on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either\n *   express or implied. See the License for the specific language governing\n *   permissions and limitations under the License.\n */\n"} should NOT have additional properties.

    at validateRuleOptions (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/node_modules/eslint/lib/shared/config-validator.js:138:1[9](https://github.com/opensearch-project/security-dashboards-plugin/runs/5196386891?check_suite_focus=true#step:11:9))
    at Object.keys.forEach.id (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/node_modules/eslint/lib/shared/config-validator.js:193:9)
    at Array.forEach (<anonymous>)
    at validateRules (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:[13](https://github.com/opensearch-project/security-dashboards-plugin/runs/5196386891?check_suite_focus=true#step:11:13))
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:[21](https://github.com/opensearch-project/security-dashboards-plugin/runs/5196386891?check_suite_focus=true#step:11:21))
    at FileEnumerator._iterateFilesRecursive (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/node_modules/eslint/lib/cli-engine/file-enumerator.js:396:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/OpenSearch-Dashboards/node_modules/eslint/lib/cli-engine/file-enumerator.js:[25](https://github.com/opensearch-project/security-dashboards-plugin/runs/5196386891?check_suite_focus=true#step:11:25)1:49)
error Command failed with exit code 2.
```

**Comment by davidlago** [comment]
This is because of a change that initially was just in `2.0` but apparently it has made it to `1.x`. The fix is what I had here for my `2.0` bump PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/892/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L31
